
import * as fc from 'fast-check';
import { authService, clearInvalidatedTokens } from '../../src/services/auth.service';
import { prisma } from '../../src/config/database';
import { validEmailArb, validPasswordArb, validNameArb } from '../helpers/generators';
import { authMiddleware } from '../../src/middleware/auth.middleware';
import { AppError, ErrorCode } from '../../src/utils/errors';

describe('Auth Property Tests', () => {
    beforeAll(async () => {
        await prisma.$connect();
    });

    afterAll(async () => {
        await prisma.$disconnect();
    });

    beforeEach(async () => {
        // Clear database
        const tablenames = await prisma.$queryRaw<
            Array<{ tablename: string }>
        >`SELECT tablename FROM pg_tables WHERE schemaname='public'`;

        const tables = tablenames
            .map(({ tablename }) => tablename)
            .filter((name) => name !== '_prisma_migrations')
            .map((name) => `"public"."${name}"`)
            .join(', ');

        if (tables.length > 0) {
            await prisma.$executeRawUnsafe(`TRUNCATE TABLE ${tables} CASCADE;`);
        }

        // Clear in-memory tokens
        clearInvalidatedTokens();
    });

    describe('Property 5: Logout invalidates token', () => {
        it('should invalidate access token after logout', async () => {
            await fc.assert(
                fc.asyncProperty(
                    validEmailArb,
                    validPasswordArb,
                    validNameArb,
                    async (email, password, name) => {
                        // 1. Register
                        const { admin } = await authService.register({
                            email,
                            password,
                            name,
                        });

                        // Clear tokens generated by register to force clean login and avoid 'iat' collision
                        await prisma.adminToken.deleteMany({ where: { adminId: admin.id } });

                        // 2. Login
                        const { tokens } = await authService.login({
                            email,
                            password,
                        });

                        // 3. Verify token is valid (not invalidated)
                        if (authService.isTokenInvalidated(tokens.accessToken)) {
                            throw new Error('Token should not be invalidated immediately after login');
                        }

                        // 4. Logout
                        await authService.logout(admin.id, tokens.accessToken);

                        // 5. Verify token is invalidated
                        if (!authService.isTokenInvalidated(tokens.accessToken)) {
                            throw new Error(`Token was not invalidated after logout. Token: ${tokens.accessToken}`);
                        }

                        // Cleanup:
                        await prisma.adminToken.deleteMany({ where: { adminId: admin.id } });
                        await prisma.admin.delete({ where: { id: admin.id } });
                    }
                ),
                { numRuns: 20 }
            );
        });
    });

    describe('Property 11: Reject unauthenticated requests', () => {
        it('should reject requests with missing or invalid tokens', async () => {
            await fc.assert(
                fc.asyncProperty(
                    fc.oneof(
                        fc.constant(undefined),
                        fc.constant(''),
                        fc.string(),
                        fc.string().map((s) => `Bearer ${s}`)
                    ),
                    async (authHeader) => {
                        const req: any = {
                            headers: {
                                authorization: authHeader,
                            },
                        };
                        const res: any = {};
                        const next = jest.fn();

                        // Use the middleware
                        await authMiddleware(req, res, next);

                        // Verify next was called with an error
                        expect(next).toHaveBeenCalled();
                        const error = next.mock.calls[0][0];

                        // We expect an Error (AppError)
                        expect(error).toBeDefined();
                        expect(error).toBeInstanceOf(AppError);

                        const appError = error as AppError;
                        // It should be 401 Unauthorized for missing/invalid tokens
                        expect(appError.statusCode).toBe(401);
                        expect([ErrorCode.UNAUTHORIZED, ErrorCode.INVALID_TOKEN]).toContain(appError.code);
                    }
                )
            );
        });
    });
});
